### PR TITLE
add syntax highlight

### PR DESCRIPTION
**Pull request by pgmmpk**
add grammar and themes to highlight church slavonic markdown syntax.

image

### CODE REVIEW

**Comment by typiconman** [comment]
@pgmmpk How can I test this?

**Comment by pgmmpk** [comment]
@typiconman To test, use debug mode:

1. Checkout repo
2. Open repo folder in VSCODE, as usual
3. Make sure that you uninstall production copy of the `vscode-church-slavonic`
4. Hit F5 in VSCODE to start "extension debugger". Expect it to open a new copy of VSCODE. This new copy will have the extension (even though its not listed in the installed ones)
5. In the second copy of VSCODE, open a sample document and play with it

Known problems:
1. Multiline `kinovar`/`wide` not highlighed. This is a known problem with VSCODE. Bold/italics have the same deficiency

**Comment by typiconman** [comment]
@pgmmpk I tried to follow your instructions, but in Step 5, I receive the following message:
`Activating extension 'pgmmpk.vscode-church-slavonic' failed: Cannot find module 'markdown-it-church-slavonic'.`

**Comment by pgmmpk** [comment]
My bad. You need to have node/npm installed and install the dependencies:

Step 3a. Install project dependencies: `npm i` from the `vscode-church-slavonic` repository

**Comment by typiconman** [comment]
Do I also have to specify the language? Because right now the syntax highlighting does not work.

Screenshot from 2019-06-26 15-14-36

**Comment by pgmmpk** [comment]
Hmm. Please make sure that you are testing the "highlights" branch of `vscode-church-slavonic`

**Comment by typiconman** [comment]
Ah, yes, you're right. My bad.

**Comment by typiconman** [comment]
Yes, it works fine. Is having both red and wide (e.g., `+=lorem ipsum=+`) supposed to do anything special?

**Comment by pgmmpk** [comment]
So far I did not find how to support nested highlights. Yes, this is another "known problem" :/

**Review by typiconman — APPROVED** [review]
LGTM.

**Comment by pgmmpk** [comment]
Extension published as version 0.1.2. Please, install/update

**Comment by typiconman** [comment]
Yes, it installs OK.

**Pull request merged**
